### ISSUE TITLE
User Story: Complete the errata process for RHEL 8 dsc-tools (0.2.0)

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#186]
https://errata.devel.redhat.com/errata/details/46522

**Comment by myersCody** [comment]
New Jira ticket opened for changing the name to dsc-tools: 
https://projects.engineering.redhat.com/browse/RCM-66263

**Comment by myersCody** [comment]
Advisory created with: https://github.com/redhat-discovery/discovery/issues/210
Advisory: https://errata.devel.redhat.com/errata/details/46522

**Comment by myersCody** [comment]
We have decided to rename the repo form `dsc-tools` to `discovery-tools`.
https://projects.engineering.redhat.com/browse/RCM-66593
