### ISSUE TITLE
Locate a Red Hat Posgres container we can use for Discovery

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#187]
@kholdaway commented on [Mon Jul 08 2019](https://github.com/redhat-discovery/discovery-installer/issues/9)

**Comment by myersCody** [comment]
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel8/postgresql-96

**Comment by myersCody** [comment]
```
podman login registry.redhat.io
podman pull registry.redhat.io/rhel8/postgresql-96
podman run --name qpc-db3 -e POSTGRESQL_PASSWORD=password POSTGRESQL_USER=postgresql POSTGRESQL_DATABASE=test -d registry.redhat.io/rhel8/postgresql-96:latest
```

⚠️ Note: 
```
For general container run, you must either specify the following environment
variables:
  POSTGRESQL_USER  POSTGRESQL_PASSWORD  POSTGRESQL_DATABASE
```
- Those variables are required in order to start the container.

**Comment by kholdaway** [comment]
I think we should legally be able to use https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel8/postgresql-96.  This is produced by Red Hat.
