### ISSUE TITLE
User Story: Build RHEL 8 discovery-server container (0.9.1)

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#195]
Make sure to include new upstream changes: 
- [x] https://github.com/quipucords/quipucords/pull/1995
- [x] https://github.com/quipucords/quipucords/pull/2002

**Comment by myersCody** [comment]
Closed with: https://github.com/redhat-discovery/discovery/pull/204
Advisory update with new build here: https://errata.devel.redhat.com/advisory/44736
