### ISSUE TITLE
Finalize docs for dsc-tools installer. 

### ISSUE THREAD

**Issue by myersCody** [redhat-discovery/discovery#222]
- [x] Enable `discovery` & `ansible`

**Assumptions Questions:**
- [x] **One:** You get the confirmation message for each package installing successfully.
- [x] **Two:** You are in a state where the server is started.
- [x] **Three:** You don't have to do that server config anymore? (readthedocs info, config the CLI connection) Or if you do, it's only if you installed the CLI on a different machine (so you have to know the IP address of the server machine)? ALTERNATIVELY you set the server-host option when you installed the CLI on a different machine--so you don't have to do the manual server config step (what I said first).
- [x] **Four:** You still have to log in to the server? (That is, you're not automagically logged in to server after installation?)
- [x] **Five:** So if the CLI is on the same machine as the server and you want to use it, you can just open a terminal, log in to the server, and qpc away? And if it is not on the same machine, then hopefully you did the number 3 ALTERNATIVELY step? And if that's true, you can just enter the qpc server login command?
- [x] **Six:** And if you want to do the GUI thing, you can connect with the loopback address from the same machine. Or you have to have the IP address (and port, if changed) if you are using the GUI from a remote machine.

**Comment by myersCody** [comment]
Example of enablement for Ansible: https://access.redhat.com/articles/3174981

What the discovery docs will most likely look like: 
```
# Discovery Enablement Docs

Register the control node with Red Hat Subscription Manager(RHSM) and subscribe to the Discovery repository:
First register your system to RHSM:
# subscription-manager register
Attach your Discovery subscription. This command will help you find the Discovery subscription:
# subscription-manager list --available
Grab the pool id of the subscription and run the following:
# subscription-manager attach --pool=<pool id here of engine subscription>
Enable the Discovery Repository:
# subscription-manager repos --enable discovery-0-for-rhel8-x86_64-rpms
Install Discovery Tools:
# yum install discovery-tools
```

**Comment by jlprevatt** [comment]
Thanks for the responses. Follow-up questions:
3. "if the user does not pass in the arguments..." The `--server-port` and `--server-host` options are documented as having defaults, so are the defaults *not* passed in? My assumption was 

- that if server/cli are on the same machine and if you took all defaults during install, the defaults would result in a working system where you would not have to run `qpc server config` because the two things that have to be configured are already configured (with the defaults, 9443 and 127.0.0.1). 

- that if server/cli are on different machines then you have to enter the IP address (and maybe the port) during cli install because jumping to a different machine using 127.0.0.1 won't work. (But...if the defaults are never right, and the first option won't work, then there should not be defaults and the user should be prompted.)

**Comment by jlprevatt** [comment]
Thanks for the background. Am I looking at the wrong version of the qpc-tools man page, then? (I have refreshed it a couple of times, but I haven't shut it down and gone back in.) CLI install shows defaults for port and IP address in this version: https://github.com/quipucords/qpc-tools/blob/master/docs/man.md, and that info helped kick off my cascade of assumptions, that if the defaults were set in both places, you would not have to do the config command.

**Comment by abaiken** [comment]
1. In the section `Other environment prerequisites` the 6th bullet down says :
```
For more information about these commands, see "Commands that are used in scans of remote network assets" in Using product discovery.
```
but as far as I can see, those sections don't exist. 
2. Under `Installing the server`: We also prompt for the red hat registry username and password. The order is registry username, registry password, server password, db password. We should also potentially mention that they should write down the passwords, as we have no recovery method. 

3. Under `Server installation options`, we also have the options for `--registry_user` and `--registry-password` that we should document.

**Comment by jlprevatt** [comment]
Follow-up to Ashley's comments 2 and 3...are those registry things currently documented in the qpc-tools man page information?

**Comment by myersCody** [comment]
> Follow-up to Ashley's comments 2 and 3...are those registry things currently documented in the qpc-tools man page information?

No, they are not documented in the `qpc-tools` man page because they are downstream only args. 

However here is the help text and what is provided downstream for those args:
```
  --registry-password RH_REGISTRY_PASSWORD
                        Set the registry.redhat.io password. If not provided,
                        user will be prompted.
  --registry-user RH_REGISTRY_USERNAME
                        Set the registry.redhat.io username
```
