### ISSUE TITLE
User Story: Create advisory for 0.2.1 release

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#226]
- [ ] Fix downstream code so installation completes successfully
- [x] Create advisory for new 0.2.1 discovery-tools RPM

Advisory: https://errata.devel.redhat.com/advisory/48164

**Comment by myersCody** [comment]
Advisory has been created: https://errata.devel.redhat.com/advisory/48164

**Comment by myersCody** [comment]
Downstream fixes are in this pr: https://github.com/redhat-discovery/discovery/pull/227

**Comment by myersCody** [comment]
New official build for downstream: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24574562
