### ISSUE TITLE
User Story: Cut downstream releases (server 0.9.2, 0.9.3 qpc CLI and tools 0.2.3) for RHEL 8.1

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#229]
Cut downstream releases (server 0.9.2 and tools 0.2.2) for RHEL 8.1

**Comment by myersCody** [comment]
I have created the bug in bugzilla for the rpms advisories. Waiting for flag to be set to `+` in order to create the advisory. I will update this comment once the advisory has been created.

**Comment by myersCody** [comment]
The advisories have been shipped live.
