### ISSUE TITLE
Build python-numpy for RHEL7.7 in BREW

### ISSUE THREAD

**Issue by myersCody** [redhat-discovery/discovery#51]

**Comment by myersCody** [comment]
I was able to find `python3-numpy` for RHEL8 in the internal pulp-dist repository. Which leads me to believe that it is currently built and working for RHEL8. Therefore, I am going to change this to be RHEL7.7 only. However I will ensure to keep the RHEL8 makefile code in the pr history in case we have to add RHEL8 back in later.

**Comment by kholdaway** [comment]
I don't see a need to keep the history.  We have many other make files with RHEL 8.

**Comment by myersCody** [comment]
Task Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21829623
Build Info: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=902258
